name: Multi-Project DevOps Common C++ Pull Request

on:
  workflow_call:
    inputs:
      source_directories:
        description: "Space separated list of source directories"
        type: string
        required: true

jobs:

  check_license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apache/skywalking-eyes@v0.4.0
        with:
          config: ".github/.licenserc.yaml"

  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: ${{ inputs.source_directories }}
          extensions: "hpp,cpp"
          clangFormatVersion: 12
          inplace: false
